# Generated by Django 5.2.7 on 2025-10-04 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disaster_type', models.CharField(choices=[('Flood', 'Flood'), ('Earthquake', 'Earthquake'), ('Storm', 'Storm'), ('Fire', 'Fire'), ('Other', 'Other')], default='Other', max_length=50)),
                ('description', models.TextField()),
                ('location_lat', models.FloatField()),
                ('location_lng', models.FloatField()),
                ('is_urgent', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
